### ISSUE TITLE
How to build irrep in vertual environment

### ISSUE THREAD

**Issue by kvineet66** [stepan-tsirkin/irrep#16]
Dear sir,
I have created virtual environment for irrep but when i am trying command
python3 -m irrep,
It is not working. Seems that the irrep is not set up in a virtual environment.

Please help me out to fix the issue.

Thanks & Regards,
Vineet Kumar Sharma
Research Scholar
IIT Hyderabad

**Comment by stepan-tsirkin** [comment]
Dear Vineet, 
in the new versions you run it as just "irrep", without "python3 -m", please read the README carefully,
