### ISSUE TITLE
Reserved filename

### ISSUE THREAD

**Issue by mikelgda** [stepan-tsirkin/irrep#30]
"aux" is a reserved word on Windows. I suggest that you change the name of `aux.py` to something else to avoid issues (i.e. you cannot pull from this repo on Windows).

**Comment by stepan-tsirkin** [comment]
Wow, couldn't even imagine to have such issues. 

@mikelgda, could you make a PR to fix this, rename in e.g. into `utility.py` (if it is not reserved on Windows ) and change all corresponding imports.

@MIraola , we will also have to update the [documetnation](http://irrep.dipc.org/documentation.aux.html)

**Comment by MIraola** [comment]
Hi,
I've updated the we documentation in the webpage. We can close the thread, right?

**Comment by stepan-tsirkin** [comment]
Thanks. Sure, let's close.
