### ISSUE TITLE
How to understand reference cell?

### ISSUE THREAD

**Issue by xuey06** [stepan-tsirkin/irrep#50]
![image](https://user-images.githubusercontent.com/51693100/187827360-0ee0195a-4ffb-4bbb-8ef3-9548f4747902.png)
Dear sir,
As explained in ref. [Computer Physics Communications 272 (2022) 108226], the relation betweent a(i) and c(i) in above figure should be $c(0)=a(0)-a(1), c(1)=a(1), c(2)=a(2)$. While, the coordinates of c(i) in this figure make me a little confused. It seems that $c(0)_1=a(0)_1-a(0)_2 \ , \ c(1)_2=a(1)_1-a(1)_2 \ , \ \cdots$. How to understand it and how to obtain the coordinates of convetional basis in BCS from the output of irrep?
Yours,
Xue

**Comment by MIraola** [comment]
Dear @xuey06 ,

thank you for opening an issue. Thanks to it I've realized that there is a bug when printing `refUC` and the relation between basis vectors of both unit cells. The bug is located in the printing step, so it does not have any effect in the calculation of traces and irreps.

I'll correct the bug asap and let you know.

**Comment by xuey06** [comment]
Thanks.

**Comment by MIraola** [comment]
Dear @xuey06 ,

the PR correcting this issue has been implemented. Thank you for your feedback.

**Comment by xuey06** [comment]
> Dear @xuey06 ,
> 
> the PR correcting this issue has been implemented. Thank you for your feedback.

Dear Sir,
 The fixed version seems to have not been upload yet?

**Comment by MIraola** [comment]
Dear @xuey06 ,

I have uploaded to pypi the version 1.8.0 of IrRep, which fixes the problem. You can now install it with
```
pip install irrep
```
(I did not upload it before because I wanted the publish version to include some other modifications I was working on)

**Comment by xuey06** [comment]
> Dear @xuey06 ,
> 
> I have uploaded to pypi the version 1.8.0 of IrRep, which fixes the problem. You can now install it with
> 
> ```
> pip install irrep
> ```
> 
> (I did not upload it before because I wanted the publish version to include some other modifications I was working on)

thanks
